### ISSUE TITLE
minus sign in the Inpiratory-Expiratory rate. 

### ISSUE THREAD

**Issue by vpesudo** [MVMSoftware/gui#16]
In the settings window, the minus button of the Inspiratory Expiratory rate is not obvious. Maybe putting the "minus" sign on the right hand side next to the "plus" one would make it more easy to spot.

**Comment by carmelopellegrino** [comment]
I thought about this when I was designing those buttons and I thought it was better to put the buttons separate so that, for example when moving, it's easy not to click on an unintended button by chance. I can make it more evident that it is a minus (it'a png file actually, so very easy to change)
