### ISSUE TITLE
target platform?

### ISSUE THREAD

**Issue by tsengj10** [MVMSoftware/gui#41]
Sorry, this was probably discussed earlier, but on the general call today, someone mentioned having training software on tablets.

Are we aiming to have the gui running on tablets, or will it always be running on a PC?

And if we should be targeting tablets, do we have a python-on-android/iOS solution in mind which will support a graphical user interface?

**Comment by carmelopellegrino** [comment]
Hi Jeff,

I didn't participate to the today general meeting so I missed this news.

Training could be done in many different ways, using for example standard PCs, which are currently supported. For example, we have for sure got it run on both macOS and Linux, apart from Raspberry Pi, and I'm quite confident that eventually it will work on Windows.

So the answer is no: we don't have a python-on-android/iOS solution in mind.

**Comment by tsengj10** [comment]
Thanks.  We may want to get some clarity on this at some point, i.e., what device platforms are most common where the ventilator might be used.  In the meantime, however, it shouldn't affect current development; worst case, the current code is the invaluable prototype which will guide any re-coding.

**Comment by carmelopellegrino** [comment]
Thank you for having raised the point!
I close the issue for now.
