### ISSUE TITLE
change the color of the widget showing a parameter that is out of range

### ISSUE THREAD

**Issue by carmelopellegrino** [MVMSoftware/gui#6]

**Comment by javerom** [comment]
Basic functionality was implemented. Pull request pending.

**Comment by carmelopellegrino** [comment]
Great! I checked out the branch and it works with the simulated data. I just realised that it flashes very quickly, being them random values. Would it be possible to keep the red color until the user clicks on the whole rectangular area?

**Comment by javerom** [comment]
Yup can do that

**Comment by javerom** [comment]
This features has been added.

**Comment by carmelopellegrino** [comment]
Great job, it works perfectly!
