### ISSUE TITLE
Add additional settable params

### ISSUE THREAD

**Issue by marcodeltutto** [MVMSoftware/gui#70]
These are all the settings we should have:

> Automatic
> Respiratory Rate
> Insp/Expr Ratio it has to be in the form 1:x (right exactly 1:x)
> Insp. Pressure (mbar)
> Peep (mbar)

> Assisted
> Support Pressure (mbar)
> Peep (mbar)
> Pressure Trigger (arbirtary unit between 1 and 100)
> Flow trigger (%)
> Backup use a toggle button (green/red)

**Comment by carmelopellegrino** [comment]
addressed in pr #67
