### ISSUE TITLE
correct qt signal emission in threading_utils

### ISSUE THREAD

**Issue by carmelopellegrino** [MVMSoftware/gui#9]
in `gui/communication/threading_utils.py` in `Worker.run` (currently at line number 74) the `self.signals.result.emit` function is called with one only argument while it expects two

**Comment by marcodeltutto** [comment]
Can this be closed?

**Comment by carmelopellegrino** [comment]
I've tentatively added a `None` argument to the function, but I'm not pretty sure if this is 100% correct. though it works fine...
